package Cadastrar;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;

import root.Acolito;
import root.Index;

/**
 *
 * @author me250
 */
public class Acolitos extends javax.swing.JInternalFrame {


    //VARIAVEIS---------------------------------------------------------
    public static root.Acolito acolito = new root.Acolito();
    private static Map<String, List<String>> Disponibilidade = new HashMap<>();


    //GETTERS AND SETTERS---------------------------------------------------------
    public static Map<String, List<String>> getDisponibilidade() {
        return Disponibilidade;
    }

    public static void setDisponibilidade(Map<String, List<String>> disponibilidade) {
        Disponibilidade = disponibilidade;
    }


    //CONTRUTOR -------------------------------------------------------------------------
    public Acolitos() {
        initComponents();
    }


    //INICIALIZAÇÃO DOS COMPONENTES -------------------------------------------------------------------------
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        NomeTXT = new javax.swing.JTextField();
        SManhaCheck = new javax.swing.JCheckBox();
        STardeCheck = new javax.swing.JCheckBox();
        SNoiteCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        DomingoOito = new javax.swing.JCheckBox();
        DomingoDez = new javax.swing.JCheckBox();
        DomingoDezoito = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SabadoManha = new javax.swing.JCheckBox();
        SabadoTarde = new javax.swing.JCheckBox();
        SabadoNoite = new javax.swing.JCheckBox();
        EnviarButton = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        SalvarButton = new javax.swing.JButton();

        NomeLabel.setText("Nome");

        SManhaCheck.setText("manhã");

        STardeCheck.setText("tarde");

        SNoiteCheck.setText("noite");

        jLabel4.setText("Domingo");

        DomingoOito.setText("08hrs");

        DomingoDez.setText("10hrs");

        DomingoDezoito.setText("18hrs");

        jLabel9.setText("Semana");

        jLabel11.setText("Sábado");

        SabadoManha.setText("manhã");

        SabadoTarde.setText("tarde");

        SabadoNoite.setText("noite");

        EnviarButton.setText("Enviar");
        EnviarButton.addActionListener(this::EnviarButtonActionPerformed);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        SalvarButton.setText("Salvar");
        SalvarButton.setEnabled(false);
        SalvarButton.addActionListener(this::SalvarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDesktopPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(NomeLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(NomeTXT))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(SManhaCheck)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(STardeCheck)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(SNoiteCheck))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(SabadoManha)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(SabadoTarde)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(SabadoNoite))
                                                        .addComponent(EnviarButton)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(DomingoOito)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(DomingoDez)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(DomingoDezoito))
                                                        .addComponent(SalvarButton))
                                                .addGap(0, 125, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NomeLabel)
                                        .addComponent(NomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(SManhaCheck)
                                        .addComponent(STardeCheck)
                                        .addComponent(SNoiteCheck))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(SabadoManha)
                                        .addComponent(SabadoTarde)
                                        .addComponent(SabadoNoite))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel10))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(DomingoOito)
                                                        .addComponent(DomingoDez)
                                                        .addComponent(DomingoDezoito))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EnviarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SalvarButton)
                                .addContainerGap(15, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // FUNÇÕES  -------------------------------------------------------------------------



    // MODELAGEM PARA NÃO DUPLICAR DIAS
    private void adicionarSemDuplicar(Map<String, List<String>> selecionados, String dia, String horario) {
        selecionados.putIfAbsent(dia, new ArrayList<>());

        if (!selecionados.get(dia).contains(horario)) {
            selecionados.get(dia).add(horario);
        }
    }



    // ONCLICK FUNCTIONS - CADASTRO -----------------------------------------------------------------------------



    // FUNÇÃO PRINCIPAL PARA CADASTROS
    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EnviarButtonActionPerformed
        try {
            SalvarButton.setEnabled(true);
            acolito.setNome(NomeTXT.getText());
            if (SabadoManha.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Sabado", "MANHA");
            }
            if (SabadoTarde.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Sabado", "TARDE");
            }
            if (SabadoNoite.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Sabado", "NOITE");
            }
            if (DomingoOito.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Domingo", "8");
            }
            if (DomingoDez.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Domingo", "10");
            }
            if (DomingoDezoito.isSelected()) {
                adicionarSemDuplicar(Disponibilidade, "Domingo", "18");
            }
            if (SManhaCheck.isSelected() || STardeCheck.isSelected() || SNoiteCheck.isSelected()) {
                PegaDias tela = new PegaDias(SManhaCheck.isSelected(), STardeCheck.isSelected(),
                        SNoiteCheck.isSelected());
                getDesktopPane().add(tela);
                tela.setVisible(true);
                return;
            }

        } catch (UnsupportedOperationException e) {
            NomeTXT.setText("");
        }
    }// GEN-LAST:event_EnviarButtonActionPerformed

    // Salva o acólito no JSON
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SalvarButtonActionPerformed
        acolito.setDisponibilidade(Disponibilidade);
        List<Acolito> acolitos = Index.pegaAcolitos();
        acolitos.add(acolito);
        Index.salvaJSON(acolitos, "C:\\Users\\me250\\projetos\\codolito-master\\src\\main\\java\\JSON\\acolitos.json",
                "Acólito");
        JOptionPane.showMessageDialog(this, "Acólito salvo com sucesso!");
        this.dispose();

    }// GEN-LAST:event_SalvarButtonActionPerformed




    //CRIAÇÃO DOS COMPONENTES ----------------------------------------------------------------------------


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DomingoDez;
    private javax.swing.JCheckBox DomingoDezoito;
    private javax.swing.JCheckBox DomingoOito;
    private javax.swing.JButton EnviarButton;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTXT;
    private javax.swing.JCheckBox SManhaCheck;
    private javax.swing.JCheckBox SNoiteCheck;
    private javax.swing.JCheckBox STardeCheck;
    private javax.swing.JCheckBox SabadoManha;
    private javax.swing.JCheckBox SabadoNoite;
    private javax.swing.JCheckBox SabadoTarde;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    //FIM --------------------------------------------------------------------------
}
