/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cadastrar;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import root.Missa;
import root.Index;

/**
 *
 * @author me250
 */
public class MissasFixas extends javax.swing.JInternalFrame {

    private List<Missa> missasFixas = new ArrayList<>();

    /**
     * Creates new form MissasFixas
     */
    public MissasFixas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DomingoLabel = new javax.swing.JLabel();
        DomingoTXT = new javax.swing.JTextField();
        QuartaLabel = new javax.swing.JLabel();
        QuartaTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SalvarButton = new javax.swing.JButton();
        EnviarButton = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DomingoLabel.setText("Primeiro domingo");
        getContentPane().add(DomingoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(DomingoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, 144, -1));

        QuartaLabel.setText("Primeira Quarta");
        getContentPane().add(QuartaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));
        getContentPane().add(QuartaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 46, 144, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 6, -1, 319));

        SalvarButton.setText("Salvar");
        SalvarButton.setEnabled(false);
        SalvarButton.addActionListener(this::SalvarButtonActionPerformed);
        getContentPane().add(SalvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, -1, -1));

        EnviarButton.setText("Enviar");
        EnviarButton.addActionListener(this::EnviarButtonActionPerformed);
        getContentPane().add(EnviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Funções

    // pega dias do mês a partir do primeiro dia
    public static int[] pegaDiasMes(int primeiroDia) {
        List<Integer> diasMes = new ArrayList<>();
        int dia = primeiroDia;
        while (dia <= 31) {
            diasMes.add(dia);
            dia += 7;
        }
        return diasMes.stream()
                .mapToInt(Integer::intValue)
                .toArray();
    }

    // cadastra missas fixas de quartas, sextas e sábados
    public static List<Missa> cadastrarMissas(String semana, int time, int[] dias) {
        List<Missa> missas = new ArrayList<>();
        for (int dia : dias) {
            Missa missa = new Missa(dia, semana, time, "-");
            missas.add(missa);
        }
        return missas;
    }

    // cadastra missas fixas dos domingos
    public static List<Missa> CadastrarDomingos(int[] dias) {
        List<Missa> missas = new ArrayList<>();
        for (int dia : dias) {
            if (dia == dias[0]) {
                Missa dom1 = new Missa(dia, "Domingo", 8, "-");
                Missa dom2 = new Missa(dia, "Domingo", 10, "Missa da Família");
                Missa dom3 = new Missa(dia, "Domingo", 18,
                        "Adoração ao Santíssimo Sacramento");
                missas.add(dom1);
                missas.add(dom2);
                missas.add(dom3);
                continue;
            }
            if (dia == dias[2]) {
                Missa dom1 = new Missa(dia, "Domingo", 8, "Missa do Dizimista");
                Missa dom2 = new Missa(dia, "Domingo", 10, "Missa do Dizimista");
                Missa dom3 = new Missa(dia, "Domingo", 18, "Missa do Dizimista");
                missas.add(dom1);
                missas.add(dom2);
                missas.add(dom3);
                continue;
            }
            if (dia == dias[3]) {
                Missa dom1 = new Missa(dia, "Domingo", 8, "-");
                Missa dom2 = new Missa(dia, "Domingo", 10, "Batismos");
                Missa dom3 = new Missa(dia, "Domingo", 18, "Missa Jovem");
                missas.add(dom1);
                missas.add(dom2);
                missas.add(dom3);
                continue;
            }
            Missa dom1 = new Missa(dia, "Domingo", 8, "-");
            Missa dom2 = new Missa(dia, "Domingo", 10, "-");
            Missa dom3 = new Missa(dia, "Domingo", 18, "-");
            missas.add(dom1);
            missas.add(dom2);
            missas.add(dom3);
        }
        return missas;
    }

    // apresenta na tabela as missas fixas cadastradas
    public void apresentaMissas(List<Missa> missas) {
        String[] colunas = { "dia", "semana", "hora", "celebrações" };
        List<String[]> lista = new ArrayList<>();

        for (Missa m : missas) {
            String[] linha = { String.valueOf(m.getDia()), m.getSemana(), String.valueOf(m.getTime()),
                    m.getCelebrações() };
            lista.add(linha);
        }

        String[][] dados = lista.toArray(new String[0][]);

        jTable1.setModel(
                new javax.swing.table.DefaultTableModel(
                        dados,
                        colunas));

    }

    // ONCLICK FUNCTIONS
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SalvarButtonActionPerformed
        List<Missa> missas = Index.pegaMissa();
        missas.addAll(missasFixas);
        Index.salvaJSON(missas,
                "C:\\Users\\me250\\projetos\\codolito-master\\src\\main\\java\\JSON\\missas.json",
                "Missa Fixas");
        MissasFixas.this.dispose();
    }// GEN-LAST:event_SalvarButtonActionPerformed

    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EnviarButtonActionPerformed
        SalvarButton.setEnabled(true);
        int Domingo = Integer.parseInt(DomingoTXT.getText());
        int Quarta = Integer.parseInt(QuartaTXT.getText());
        int[] domingos = pegaDiasMes(Domingo);
        missasFixas.addAll(CadastrarDomingos(domingos));
        int[] quartas = pegaDiasMes(Quarta);
        missasFixas.addAll(cadastrarMissas("Quarta", 20, quartas));
        int[] sextas = pegaDiasMes(Quarta + 2);
        missasFixas.addAll(cadastrarMissas("Sexta", 15, sextas));
        int[] sabados = pegaDiasMes(Quarta + 3);
        missasFixas.addAll(cadastrarMissas("Sábado", 19, sabados));
        missasFixas.sort(Comparator.comparing(Missa::getDia));
        apresentaMissas(missasFixas);
    }// GEN-LAST:event_EnviarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DomingoLabel;
    private javax.swing.JTextField DomingoTXT;
    private javax.swing.JButton EnviarButton;
    private javax.swing.JLabel QuartaLabel;
    private javax.swing.JTextField QuartaTXT;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
