/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cadastrar;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author me250
 */
public class PegaDias extends javax.swing.JInternalFrame {

    // VARIAVEIS-------------------------------------------------------
    public Map<String, List<String>> selecionados;
    Boolean manha = false, tarde = false, noite = false;

    // CONSTRUTOR----------------------------------------------------------------
    public PegaDias(Boolean manha, Boolean tarde, Boolean noite) {
        initComponents();

        selecionados = new HashMap<>();

        this.manha = manha;
        this.tarde = tarde;
        this.noite = noite;

        SelecionarDias();
    }

    // INCIALIZAÇÃO--------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SegundaLabel = new javax.swing.JLabel();
        SegundaManha = new javax.swing.JCheckBox();
        SegundaTarde = new javax.swing.JCheckBox();
        SegundaNoite = new javax.swing.JCheckBox();
        TerçaLabel = new javax.swing.JLabel();
        TercaManha = new javax.swing.JCheckBox();
        TercaTarde = new javax.swing.JCheckBox();
        TercaNoite = new javax.swing.JCheckBox();
        QuartaLabel = new javax.swing.JLabel();
        QuartaManha = new javax.swing.JCheckBox();
        QuartaTarde = new javax.swing.JCheckBox();
        QuartaNoite = new javax.swing.JCheckBox();
        QuintaLabel = new javax.swing.JLabel();
        QuintaManha = new javax.swing.JCheckBox();
        QuintaTarde = new javax.swing.JCheckBox();
        QuintaNoite = new javax.swing.JCheckBox();
        SextaLabel = new javax.swing.JLabel();
        SextaManha = new javax.swing.JCheckBox();
        SextaTarde = new javax.swing.JCheckBox();
        SextaNoite = new javax.swing.JCheckBox();
        EnviarButton = new javax.swing.JButton();

        SegundaLabel.setText("Segunda");

        SegundaManha.setText("Manhã");

        SegundaTarde.setText("Tarde");

        SegundaNoite.setText("Noite");

        TerçaLabel.setText("Terça");

        TercaManha.setText("Manhã");

        TercaTarde.setText("Tarde");

        TercaNoite.setText("Noite");

        QuartaLabel.setText("Quarta");

        QuartaManha.setText("Manhã");

        QuartaTarde.setText("Tarde");

        QuartaNoite.setText("Noite");

        QuintaLabel.setText("Quinta");

        QuintaManha.setText("Manhã");

        QuintaTarde.setText("Tarde");

        QuintaNoite.setText("Noite");

        SextaLabel.setText("Sexta");

        SextaManha.setText("Manhã");

        SextaTarde.setText("Tarde");

        SextaNoite.setText("Noite");

        EnviarButton.setText("Enviar");
        EnviarButton.addActionListener(this::EnviarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SegundaLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(SegundaManha)
                                                .addGap(18, 18, 18)
                                                .addComponent(SegundaTarde)
                                                .addGap(18, 18, 18)
                                                .addComponent(SegundaNoite))
                                        .addComponent(TerçaLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(TercaManha)
                                                .addGap(18, 18, 18)
                                                .addComponent(TercaTarde)
                                                .addGap(18, 18, 18)
                                                .addComponent(TercaNoite))
                                        .addComponent(QuartaLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(QuartaManha)
                                                .addGap(18, 18, 18)
                                                .addComponent(QuartaTarde)
                                                .addGap(18, 18, 18)
                                                .addComponent(QuartaNoite))
                                        .addComponent(QuintaLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(QuintaManha)
                                                .addGap(18, 18, 18)
                                                .addComponent(QuintaTarde)
                                                .addGap(18, 18, 18)
                                                .addComponent(QuintaNoite))
                                        .addComponent(SextaLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(SextaManha)
                                                .addGap(18, 18, 18)
                                                .addComponent(SextaTarde)
                                                .addGap(18, 18, 18)
                                                .addComponent(SextaNoite))
                                        .addComponent(EnviarButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SegundaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SegundaManha)
                                        .addComponent(SegundaTarde)
                                        .addComponent(SegundaNoite))
                                .addGap(18, 18, 18)
                                .addComponent(TerçaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TercaManha)
                                        .addComponent(TercaTarde)
                                        .addComponent(TercaNoite))
                                .addGap(18, 18, 18)
                                .addComponent(QuartaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(QuartaManha)
                                        .addComponent(QuartaTarde)
                                        .addComponent(QuartaNoite))
                                .addGap(18, 18, 18)
                                .addComponent(QuintaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(QuintaManha)
                                        .addComponent(QuintaTarde)
                                        .addComponent(QuintaNoite))
                                .addGap(18, 18, 18)
                                .addComponent(SextaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SextaManha)
                                        .addComponent(SextaTarde)
                                        .addComponent(SextaNoite))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EnviarButton)
                                .addContainerGap(12, Short.MAX_VALUE)));

        pack();

    }// </editor-fold>//GEN-END:initComponents

    // FUNÇÃO PRINCIPAL
    // ONCLICK-----------------------------------------------------------------------------------------------
    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EnviarButtonActionPerformed
        String[] horarios = { "MANHA", "TARDE", "NOITE" };

        if (SegundaManha.isSelected()) {
            adicionarSemDuplicar(selecionados, "Segunda", horarios[0]);
        }
        if (SegundaTarde.isSelected()) {
            adicionarSemDuplicar(selecionados, "Segunda", horarios[1]);
        }
        if (SegundaNoite.isSelected()) {
            adicionarSemDuplicar(selecionados, "Segunda", horarios[2]);
        }
        if (TercaManha.isSelected()) {
            adicionarSemDuplicar(selecionados, "Terça", horarios[0]);
        }
        if (TercaTarde.isSelected()) {
            adicionarSemDuplicar(selecionados, "Terça", horarios[1]);
        }
        if (TercaNoite.isSelected()) {
            adicionarSemDuplicar(selecionados, "Terça", horarios[2]);
        }
        if (QuartaManha.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quarta", horarios[0]);
        }
        if (QuartaTarde.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quarta", horarios[1]);
        }
        if (QuartaNoite.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quarta", horarios[2]);
        }
        if (QuintaManha.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quinta", horarios[0]);
        }
        if (QuintaTarde.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quinta", horarios[1]);
        }
        if (QuintaNoite.isSelected()) {
            adicionarSemDuplicar(selecionados, "Quinta", horarios[2]);
        }
        if (SextaManha.isSelected()) {
            adicionarSemDuplicar(selecionados, "Sexta", horarios[0]);
        }
        if (SextaTarde.isSelected()) {
            adicionarSemDuplicar(selecionados, "Sexta", horarios[1]);
        }
        if (SextaNoite.isSelected()) {
            adicionarSemDuplicar(selecionados, "Sexta", horarios[2]);
        }
        Map<String, List<String>> disponibilidade = Acolitos.getDisponibilidade();

        disponibilidade.putAll(selecionados);

        Acolitos.setDisponibilidade(disponibilidade);
        this.dispose();
    }// GEN-LAST:event_EnviarButtonActionPerformed

    // MODELAGEM PARA SELEÇÃO DE DIAS E
    // HORARIOS------------------------------------------------------
    private void SelecionarDias() {
        if (manha) {
            SegundaManha.setSelected(true);
            TercaManha.setSelected(true);
            QuartaManha.setSelected(true);
            QuintaManha.setSelected(true);
            SextaManha.setSelected(true);
        }
        if (tarde) {
            SegundaTarde.setSelected(true);
            TercaTarde.setSelected(true);
            QuartaTarde.setSelected(true);
            QuintaTarde.setSelected(true);
            SextaTarde.setSelected(true);
        }
        if (noite) {
            SegundaNoite.setSelected(true);
            TercaNoite.setSelected(true);
            QuartaNoite.setSelected(true);
            QuintaNoite.setSelected(true);
            SextaNoite.setSelected(true);
        }
    }

    // MODELAGEM PARA NÃO DUPLICAR DIAS E
    // HORARIOS------------------------------------------------------
    private void adicionarSemDuplicar(Map<String, List<String>> selecionados, String dia, String horario) {
        selecionados.putIfAbsent(dia, new ArrayList<>());

        if (!selecionados.get(dia).contains(horario)) {
            selecionados.get(dia).add(horario);
        }
    }

    // COMPONENTES--------------------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarButton;
    private javax.swing.JLabel QuartaLabel;
    private javax.swing.JCheckBox QuartaManha;
    private javax.swing.JCheckBox QuartaNoite;
    private javax.swing.JCheckBox QuartaTarde;
    private javax.swing.JLabel QuintaLabel;
    private javax.swing.JCheckBox QuintaManha;
    private javax.swing.JCheckBox QuintaNoite;
    private javax.swing.JCheckBox QuintaTarde;
    private javax.swing.JLabel SegundaLabel;
    private javax.swing.JCheckBox SegundaManha;
    private javax.swing.JCheckBox SegundaNoite;
    private javax.swing.JCheckBox SegundaTarde;
    private javax.swing.JLabel SextaLabel;
    private javax.swing.JCheckBox SextaManha;
    private javax.swing.JCheckBox SextaNoite;
    private javax.swing.JCheckBox SextaTarde;
    private javax.swing.JCheckBox TercaManha;
    private javax.swing.JCheckBox TercaNoite;
    private javax.swing.JCheckBox TercaTarde;
    private javax.swing.JLabel TerçaLabel;
    // End of variables declaration//GEN-END:variables
}
